

trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK ${dotnetSdkVersion}'
  inputs:
    packageType: sdk
    version: '5.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
<<<<<<< HEAD
  displayName: 'Build the project - Release'
=======
  displayName: 'Build the project - ${buildConfiguration}'
>>>>>>> 0605c2148d1e8b18e4c41ba5ce64da9b5b14908d
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${buildConfiguration}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
<<<<<<< HEAD
  displayName: 'Publish the project - Release'
=======
  displayName: 'Publish the project - ${buildConfiguration}'
>>>>>>> 0605c2148d1e8b18e4c41ba5ce64da9b5b14908d
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${buildConfiguration} --output $(Build.ArtifactStagingDirectory)/${buildConfiguration}'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()